export const names = [
  {
    number: 1,
    arabic: 'ٱللَّٰهُ',
    bangla: 'আল্লাহ',
    transliteration: 'Allah',
    meaning: 'The Greatest Name',
  },
  {
    number: 2,
    arabic: 'ٱلرَّحْمَٰنُ',
    bangla: 'আর-রাহমান',
    transliteration: 'Ar-Rahman',
    meaning: 'The Most Gracious',
  },
  {
    number: 3,
    arabic: 'ٱلرَّحِيمُ',
    bangla: 'আর-রাহীম',
    transliteration: 'Ar-Raheem',
    meaning: 'The Most Merciful',
  },
  {
    number: 4,
    arabic: 'ٱلْمَلِكُ',
    bangla: 'আল-মালিক',
    transliteration: 'Al-Malik',
    meaning: 'The King, The Sovereign',
  },
  {
    number: 5,
    arabic: 'ٱلْقُدُّوسُ',
    bangla: 'আল-কুদ্দুস',
    transliteration: 'Al-Quddus',
    meaning: 'The Most Holy',
  },
  {
    number: 6,
    arabic: 'ٱلسَّلَامُ',
    bangla: 'আস-সালাম',
    transliteration: 'As-Salam',
    meaning: 'The Source of Peace',
  },
  {
    number: 7,
    arabic: 'ٱلْمُؤْمِنُ',
    bangla: 'আল-মুমিন',
    transliteration: 'Al-Mumin',
    meaning: 'The Guarantor',
  },
  {
    number: 8,
    arabic: 'ٱلْمُهَيْمِنُ',
    bangla: 'আল-মুহাইমিন',
    transliteration: 'Al-Muhaymin',
    meaning: 'The Guardian',
  },
  {
    number: 9,
    arabic: 'ٱلْعَزِيزُ',
    bangla: 'আল-আজীজ',
    transliteration: 'Al-Aziz',
    meaning: 'The Almighty',
  },
  {
    number: 10,
    arabic: 'ٱلْجَبَّارُ',
    bangla: 'আল-জাব্বার',
    transliteration: 'Al-Jabbar',
    meaning: 'The Compeller',
  },
  {
    number: 11,
    arabic: 'ٱلْمُتَكَبِّرُ',
    bangla: 'আল-মুতাকাব্বির',
    transliteration: 'Al-Mutakabbir',
    meaning: 'The Greatest',
  },
  {
    number: 12,
    arabic: 'ٱلْخَالِقُ',
    bangla: 'আল-খালিক',
    transliteration: 'Al-Khaliq',
    meaning: 'The Creator',
  },
  {
    number: 13,
    arabic: 'ٱلْبَارِئُ',
    bangla: 'আল-বারি',
    transliteration: 'Al-Bari'',
    meaning: 'The Maker of Order',
  },
  {
    number: 14,
    arabic: 'ٱلْمُصَوِّرُ',
    bangla: 'আল-মুছাওউইর',
    transliteration: 'Al-Musawwir',
    meaning: 'The Shaper of Beauty',
  },
  {
    number: 15,
    arabic: 'ٱلْغَفَّارُ',
    bangla: 'আল-গাফফার',
    transliteration: 'Al-Ghaffar',
    meaning: 'The Forgiving',
  },
  {
    number: 16,
    arabic: 'ٱلْقَهَّارُ',
    bangla: 'আল-কাহহার',
    transliteration: 'Al-Qahhar',
    meaning: 'The Subduer',
  },
  {
    number: 17,
    arabic: 'ٱلْوَهَّابُ',
    bangla: 'আল-ওয়াহহাব',
    transliteration: 'Al-Wahhab',
    meaning: 'The Giver of All',
  },
  {
    number: 18,
    arabic: 'ٱلرَّزَّاقُ',
    bangla: 'আর-রাজ্জাক',
    transliteration: 'Ar-Razzaq',
    meaning: 'The Sustainer',
  },
  {
    number: 19,
    arabic: 'ٱلْفَتَّاحُ',
    bangla: 'আল-ফাত্তাহ',
    transliteration: 'Al-Fattah',
    meaning: 'The Opener',
  },
  {
    number: 20,
    arabic: 'ٱلْعَلِيمُ',
    bangla: 'আল-আলীম',
    transliteration: 'Al-Alim',
    meaning: 'The All-Knowing',
  },
  {
    number: 21,
    arabic: 'ٱلْقَابِضُ',
    bangla: 'আল-কাবিদ',
    transliteration: 'Al-Qabid',
    meaning: 'The Constrictor',
  },
  {
    number: 22,
    arabic: 'ٱلْبَاسِطُ',
    bangla: 'আল-বাসিত',
    transliteration: 'Al-Basit',
    meaning: 'The Reliever',
  },
  {
    number: 23,
    arabic: 'ٱلْخَافِضُ',
    bangla: 'আল-খাফিদ',
    transliteration: 'Al-Khafid',
    meaning: 'The Abaser',
  },
  {
    number: 24,
    arabic: 'ٱلرَّافِعُ',
    bangla: 'আর-রাফি'',
    transliteration: 'Ar-Rafi'',
    meaning: 'The Exalter',
  },
  {
    number: 25,
    arabic: 'ٱلْمُعِزُّ',
    bangla: 'আল-মুইজ',
    transliteration: 'Al-Muizz',
    meaning: 'The Bestower of Honors',
  },
  {
    number: 26,
    arabic: 'ٱلْمُذِلُّ',
    bangla: 'আল-মুদিল',
    transliteration: 'Al-Mudhill',
    meaning: 'The Humiliator',
  },
  {
    number: 27,
    arabic: 'ٱلسَّمِيعُ',
    bangla: 'আস-সামী'',
    transliteration: 'As-Sami'',
    meaning: 'The All-Hearing',
  },
  {
    number: 28,
    arabic: 'ٱلْبَصِيرُ',
    bangla: 'আল-বাছীর',
    transliteration: 'Al-Basir',
    meaning: 'The All-Seeing',
  },
  {
    number: 29,
    arabic: 'ٱلْحَكَمُ',
    bangla: 'আল-হাকাম',
    transliteration: 'Al-Hakam',
    meaning: 'The Judge',
  },
  {
    number: 30,
    arabic: 'ٱلْعَدْلُ',
    bangla: 'আল-আদল',
    transliteration: 'Al-Adl',
    meaning: 'The Just',
  },
  {
    number: 31,
    arabic: 'ٱللَّطِيفُ',
    bangla: 'আল-লাতীফ',
    transliteration: 'Al-Latif',
    meaning: 'The Subtle One',
  },
  {
    number: 32,
    arabic: 'ٱلْخَبِيرُ',
    bangla: 'আল-খাবীর',
    transliteration: 'Al-Khabir',
    meaning: 'The All-Aware',
  },
  {
    number: 33,
    arabic: 'ٱلْحَلِيمُ',
    bangla: 'আল-হালীম',
    transliteration: 'Al-Halim',
    meaning: 'The Forbearing',
  },
  {
    number: 34,
    arabic: 'ٱلْعَظِيمُ',
    bangla: 'আল-আজীম',
    transliteration: 'Al-Azim',
    meaning: 'The Magnificent',
  },
  {
    number: 35,
    arabic: 'ٱلْغَفُورُ',
    bangla: 'আল-গাফুর',
    transliteration: 'Al-Ghafur',
    meaning: 'The Forgiver and Hider of Faults',
  },
  {
    number: 36,
    arabic: 'ٱلشَّكُورُ',
    bangla: 'আশ-শাকুর',
    transliteration: 'Ash-Shakur',
    meaning: 'The Rewarder of Thankfulness',
  },
  {
    number: 37,
    arabic: 'ٱلْعَلِيُّ',
    bangla: 'আল-আলী',
    transliteration: 'Al-Ali',
    meaning: 'The Highest',
  },
  {
    number: 38,
    arabic: 'ٱلْكَبِيرُ',
    bangla: 'আল-কাবীর',
    transliteration: 'Al-Kabir',
    meaning: 'The Greatest',
  },
  {
    number: 39,
    arabic: 'ٱلْحَفِيظُ',
    bangla: 'আল-হাফীজ',
    transliteration: 'Al-Hafiz',
    meaning: 'The Preserver',
  },
  {
    number: 40,
    arabic: 'ٱلْمُقِيتُ',
    bangla: 'আল-মুকীত',
    transliteration: 'Al-Muqit',
    meaning: 'The Nourisher',
  },
  {
    number: 41,
    arabic: 'ٱلْحَسِيبُ',
    bangla: 'আল-হাসীব',
    transliteration: 'Al-Hasib',
    meaning: 'The Accounter',
  },
  {
    number: 42,
    arabic: 'ٱلْجَلِيلُ',
    bangla: 'আল-জালীল',
    transliteration: 'Al-Jalil',
    meaning: 'The Mighty',
  },
  {
    number: 43,
    arabic: 'ٱلْكَرِيمُ',
    bangla: 'আল-কারীম',
    transliteration: 'Al-Karim',
    meaning: 'The Generous',
  },
  {
    number: 44,
    arabic: 'ٱلرَّقِيبُ',
    bangla: 'আর-রাকীব',
    transliteration: 'Ar-Raqib',
    meaning: 'The Watchful One',
  },
  {
    number: 45,
    arabic: 'ٱلْمُجِيبُ',
    bangla: 'আল-মুজীব',
    transliteration: 'Al-Mujib',
    meaning: 'The Responder to Prayer',
  },
  {
    number: 46,
    arabic: 'ٱلْوَاسِعُ',
    bangla: 'আল-ওয়াসি'',
    transliteration: 'Al-Wasi'',
    meaning: 'The All-Comprehending',
  },
  {
    number: 47,
    arabic: 'ٱلْحَكِيمُ',
    bangla: 'আল-হাকীম',
    transliteration: 'Al-Hakim',
    meaning: 'The Perfectly Wise',
  },
  {
    number: 48,
    arabic: 'ٱلْوَدُودُ',
    bangla: 'আল-ওয়াদুদ',
    transliteration: 'Al-Wadud',
    meaning: 'The Loving One',
  },
  {
    number: 49,
    arabic: 'ٱلْمَجِيدُ',
    bangla: 'আল-মাজীদ',
    transliteration: 'Al-Majid',
    meaning: 'The Majestic One',
  },
  {
    number: 50,
    arabic: 'ٱلْبَاعِثُ',
    bangla: 'আল-বাইছ',
    transliteration: 'Al-Baith',
    meaning: 'The Resurrector',
  },
  {
    number: 51,
    arabic: 'ٱلشَّهِيدُ',
    bangla: 'আশ-শাহীদ',
    transliteration: 'Ash-Shahid',
    meaning: 'The Witness',
  },
  {
    number: 52,
    arabic: 'ٱلْحَقُّ',
    bangla: 'আল-হাক্ক',
    transliteration: 'Al-Haqq',
    meaning: 'The Truth',
  },
  {
    number: 53,
    arabic: 'ٱلْوَكِيلُ',
    bangla: 'আল-ওয়াকীল',
    transliteration: 'Al-Wakil',
    meaning: 'The Trustee',
  },
  {
    number: 54,
    arabic: 'ٱلْقَوِيُّ',
    bangla: 'আল-ক্বাওয়ী',
    transliteration: 'Al-Qawiyy',
    meaning: 'The Possessor of All Strength',
  },
  {
    number: 55,
    arabic: 'ٱلْمَتِينُ',
    bangla: 'আল-মাতীন',
    transliteration: 'Al-Matin',
    meaning: 'The Forceful One',
  },
  {
    number: 56,
    arabic: 'ٱلْوَلِيُّ',
    bangla: 'আল-ওয়ালী',
    transliteration: 'Al-Waliyy',
    meaning: 'The Governor',
  },
  {
    number: 57,
    arabic: 'ٱلْحَمِيدُ',
    bangla: 'আল-হামীদ',
    transliteration: 'Al-Hamid',
    meaning: 'The Praiseworthy',
  },
  {
    number: 58,
    arabic: 'ٱلْمُحْصِيُ',
    bangla: 'আল-মুহছী',
    transliteration: 'Al-Muhsi',
    meaning: 'The Accounter of All',
  },
  {
    number: 59,
    arabic: 'ٱلْمُبْدِئُ',
    bangla: 'আল-মুবদি',
    transliteration: 'Al-Mubdi',
    meaning: 'The Producer, Originator, and Initiator of All',
  },
  {
    number: 60,
    arabic: 'ٱلْمُعِيدُ',
    bangla: 'আল-মুইদ',
    transliteration: 'Al-Muid',
    meaning: 'The Reinstater Who Brings Back All',
  },
  {
    number: 61,
    arabic: 'ٱلْمُحْيِى',
    bangla: 'আল-মুহয়ী',
    transliteration: 'Al-Muhyi',
    meaning: 'The Giver of Life',
  },
  {
    number: 62,
    arabic: 'ٱلْمُمِيتُ',
    bangla: 'আল-মুমীত',
    transliteration: 'Al-Mumit',
    meaning: 'The Bringer of Death',
  },
  {
    number: 63,
    arabic: 'ٱلْحَىُّ',
    bangla: 'আল-হাইয়্যু',
    transliteration: 'Al-Hayy',
    meaning: 'The Ever Living',
  },
  {
    number: 64,
    arabic: 'ٱلْقَيُّومُ',
    bangla: 'আল-ক্বাইয়্যূম',
    transliteration: 'Al-Qayyum',
    meaning: 'The Self-Subsisting Sustainer of All',
  },
  {
    number: 65,
    arabic: 'ٱلْوَاجِدُ',
    bangla: 'আল-ওয়াজিদ',
    transliteration: 'Al-Wajid',
    meaning: 'The Perceiver',
  },
  {
    number: 66,
    arabic: 'ٱلْمَاجِدُ',
    bangla: 'আল-মাজিদ',
    transliteration: 'Al-Majid',
    meaning: 'The Illustrious, the Magnificent',
  },
  {
    number: 67,
    arabic: 'ٱلْوَاحِدُ',
    bangla: 'আল-ওয়াহিদ',
    transliteration: 'Al-Wahid',
    meaning: 'The One, The Unique, The Single',
  },
  {
    number: 68,
    arabic: 'ٱلْأَحَدُ',
    bangla: 'আল-আহাদ',
    transliteration: 'Al-Ahad',
    meaning: 'The One, the All Inclusive, The Indivisible',
  },
  {
    number: 69,
    arabic: 'ٱلصَّمَدُ',
    bangla: 'আছ-ছামাদ',
    transliteration: 'As-Samad',
    meaning: 'The Self Sufficient, the Impregnable',
  },
  {
    number: 70,
    arabic: 'ٱلْقَادِرُ',
    bangla: 'আল-ক্বাদির',
    transliteration: 'Al-Qadir',
    meaning: 'The All Powerful',
  },
  {
    number: 71,
    arabic: 'ٱلْمُقْتَدِرُ',
    bangla: 'আল-মুক্বতাদির',
    transliteration: 'Al-Muqtadir',
    meaning: 'The Creator of All Power',
  },
  {
    number: 72,
    arabic: 'ٱلْمُقَدِّمُ',
    bangla: 'আল-মুক্বাদ্দিম',
    transliteration: 'Al-Muqaddim',
    meaning: 'The Expediter, He who brings forward',
  },
  {
    number: 73,
    arabic: 'ٱلْمُؤَخِّرُ',
    bangla: 'আল-মুআখখির',
    transliteration: 'Al-Muakhkhir',
    meaning: 'The Delayer, He who puts far away',
  },
  {
    number: 74,
    arabic: 'ٱلْأَوَّلُ',
    bangla: 'আল-আওয়াল',
    transliteration: 'Al-Awwal',
    meaning: 'The First',
  },
  {
    number: 75,
    arabic: 'ٱلْآخِرُ',
    bangla: 'আল-আখির',
    transliteration: 'Al-Akhir',
    meaning: 'The Last',
  },
  {
    number: 76,
    arabic: 'ٱلظَّاهِرُ',
    bangla: 'আজ-জাহির',
    transliteration: 'Az-Zahir',
    meaning: 'The Manifest',
  },
  {
    number: 77,
    arabic: 'ٱلْبَاطِنُ',
    bangla: 'আল-বাতিন',
    transliteration: 'Al-Batin',
    meaning: 'The Hidden',
  },
  {
    number: 78,
    arabic: 'ٱلْوَالِي',
    bangla: 'আল-ওয়ালী',
    transliteration: 'Al-Wali',
    meaning: 'The Protecting Friend, Patron, and Helper',
  },
  {
    number: 79,
    arabic: 'ٱلْمُتَعَالِي',
    bangla: 'আল-মুতাআলী',
    transliteration: 'Al-Mutaali',
    meaning: 'The Supreme One',
  },
  {
    number: 80,
    arabic: 'ٱلْبَرُّ',
    bangla: 'আল-বারর',
    transliteration: 'Al-Barr',
    meaning: 'The Source of All Goodness',
  },
  {
    number: 81,
    arabic: 'ٱلتَّوَّابُ',
    bangla: 'আত-তাওয়াব',
    transliteration: 'At-Tawwab',
    meaning: 'The Ever-Returning, Ever-Relenting',
  },
  {
    number: 82,
    arabic: 'ٱلْمُنْتَقِمُ',
    bangla: 'আল-মুনতাক্বিম',
    transliteration: 'Al-Muntaqim',
    meaning: 'The Avenger',
  },
  {
    number: 83,
    arabic: 'ٱلْعَفُوُّ',
    bangla: 'আল-আফুওও',
    transliteration: 'Al-Afuww',
    meaning: 'The Pardoner, The Effacer of Sins',
  },
  {
    number: 84,
    arabic: 'ٱلرَّؤُفُ',
    bangla: 'আর-রাউফ',
    transliteration: 'Ar-Rauf',
    meaning: 'The Compassionate, The All Pitying',
  },
  {
    number: 85,
    arabic: 'مَالِكُ ٱلْمُلْكِ',
    bangla: 'মালিকুল মুলক',
    transliteration: 'Malik-al-Mulk',
    meaning: 'The Owner of All Sovereignty',
  },
  {
    number: 86,
    arabic: 'ذُو ٱلْجَلَالِ وَٱلْإِكْرَامِ',
    bangla: 'যুল জালালি ওয়াল ইকরাম',
    transliteration: 'Dhul-Jalali-wal-Ikram',
    meaning: 'The Lord of Majesty and Generosity',
  },
  {
    number: 87,
    arabic: 'ٱلْمُقْسِطُ',
    bangla: 'আল-মুক্বসিত',
    transliteration: 'Al-Muqsit',
    meaning: 'The Equitable One',
  },
  {
    number: 88,
    arabic: 'ٱلْجَامِعُ',
    bangla: 'আল-জামি'',
    transliteration: 'Al-Jami'',
    meaning: 'The Gatherer, the Unifier',
  },
  {
    number: 89,
    arabic: 'ٱلْغَنِيُّ',
    bangla: 'আল-গানী',
    transliteration: 'Al-Ghani',
    meaning: 'The All Rich, The Independent',
  },
  {
    number: 90,
    arabic: 'ٱلْمُغْنِيُّ',
    bangla: 'আল-মুগনী',
    transliteration: 'Al-Mughni',
    meaning: 'The Enricher, The Emancipator',
  },
  {
    number: 91,
    arabic: 'ٱلْمَانِعُ',
    bangla: 'আল-মানি'',
    transliteration: 'Al-Mani'',
    meaning: 'The Withholder, The Shielder, The Defender',
  },
  {
    number: 92,
    arabic: 'ٱلضَّارُّ',
    bangla: 'আদ-দারর',
    transliteration: 'Ad-Darr',
    meaning: 'The Distressor, The Harmer',
  },
  {
    number: 93,
    arabic: 'ٱلنَّافِعُ',
    bangla: 'আন-নাফি'',
    transliteration: 'An-Nafi'',
    meaning: 'The Propitious, The Benefactor',
  },
  {
    number: 94,
    arabic: 'ٱلنُّورُ',
    bangla: 'আন-নূর',
    transliteration: 'An-Nur',
    meaning: 'The Light',
  },
  {
    number: 95,
    arabic: 'ٱلْهَادِي',
    bangla: 'আল-হাদী',
    transliteration: 'Al-Hadi',
    meaning: 'The Guide',
  },
  {
    number: 96,
    arabic: 'ٱلْبَدِيعُ',
    bangla: 'আল-বাদী'',
    transliteration: 'Al-Badi'',
    meaning: 'The Incomparable, The Originator',
  },
  {
    number: 97,
    arabic: 'ٱلْبَاقِي',
    bangla: 'আল-বাক্বী',
    transliteration: 'Al-Baqi',
    meaning: 'The Ever Enduring and Immutable',
  },
  {
    number: 98,
    arabic: 'ٱلْوَارِثُ',
    bangla: 'আল-ওয়ারিছ',
    transliteration: 'Al-Warith',
    meaning: 'The Heir, The Inheritor of All',
  },
  {
    number: 99,
    arabic: 'ٱلرَّشِيدُ',
    bangla: 'আর-রাশীদ',
    transliteration: 'Ar-Rashid',
    meaning: 'The Guide, Infallible Teacher, and Knower',
  },
  {
    number: 100,
    arabic: 'ٱلصَّبُورُ',
    bangla: 'আছ-ছাবূর',
    transliteration: 'As-Sabur',
    meaning: 'The Patient One',
  },
]

